### ISSUE TITLE
error on sphinx using mysql interface

### ISSUE THREAD

**Issue by tisdall** [mwarkentin/django-watchman#107]
I upgraded to Django 1.8 and am now getting the following exception on one of my databases:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/watchman/decorators.py", line 17, in wrapped
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/watchman/checks.py", line 39, in _check_database
    connections[database].introspection.table_names()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 57, in table_names
    return get_names(cursor)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 53, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/introspection.py", line 48, in get_table_list
    cursor.execute("SHOW FULL TABLES")
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "sphinxql: syntax error, unexpected IDENT, expecting VARIABLES near 'FULL TABLES'")
```

The database is [sphinx](http://sphinxsearch.com/) using the MySQL interface.  So, it behaves a little different than a regular MySQL db, but has a listing in the `DATABASES` settings like the rest.

I'm guessing I'll have to exclude this database connection using `WATCHMAN_DATABASES` and then write my own test.  Do you have any suggestions for testing the database in an alternative fashion?

I'll see what I can figure out and report back here...  I'm really just reporting the issue in case anyone else has a similar problem or if there's an existing solution.  The default test did work fine in Django 1.7 so I'm not sure what changed.

**Comment by mwarkentin** [comment]
@tisdall Thanks for the report - I'm not familiar with sphinx. The test we use for django-watchman is quite simple, just use the ORM to try to list the available tables on the database: https://github.com/mwarkentin/django-watchman/blob/master/watchman/checks.py#L39

Wonder what changed in the ORM in 1.8 to trigger this..

**Comment by tisdall** [comment]
Going through the Django code, it looks like it used to call `SHOW TABLES` with MySQL but now calls `SHOW FULL TABLES` (which doesn't work in sphinx).  The change as to add the ability to filter out views from the list.

I wrote my own check that calls `SHOW TABLES` like it did before and then just excluded it from the regular database check.

Feel free to close this issue if you'd like...  The issue isn't really with django-watchman, but I thought I'd file an issue in case anyone else had a similar issue.

My test for sphinx is basically doing this:
```
    cursor = connections['sphinx'].cursor()
    cursor.execute("SHOW TABLES")
    result = [row[0] for row in cursor.fetchall()]
```

**Comment by mwarkentin** [comment]
@tisdall is there anything in the DATABASES object that would indicate that the connection is for sphinx and not MySQL?

**Comment by tisdall** [comment]
Hmm..  There might be some way to distinguish that it's sphinx and not regular mysql, I'd have to look into it.  However, out of all the database connections in all the Django instances I'd suspect less than 1% are Sphinx.  I don't think it's a good idea to try sending SQL commands to try to distinguish if it's Sphinx.  I don't know if there's any sort of passive way of detecting...  Is there any sort of "meta" information on existing database connections?

If you really wanted to, I guess you could put a try-except around the `table_names()` call to catch the `ProgrammingError` and then try doing `SHOW TABLES` instead.  However, this seems like a pretty far edge-case to be supporting.

**Comment by mwarkentin** [comment]
Agreed, I was really just curious if there was anything in your databases dict which would indicate that it was a sphinx db instead of MySQL. 

Going to close this, thanks for the report!
