### ISSUE TITLE
Check decorator could take name

### ISSUE THREAD

**Issue by Ismael** [mwarkentin/django-watchman#126]
This is the problem I've got:

I want to write a simple check, and I want to use the check decorator to capture exceptions, so I do:
```
@check
def check_something():
   return {'something': {'ok': True}}
```

But if there's an exception it will return {ok, error, stacktrace} and I will lose my 'something' hierarchy.

So in order to use the decorator, I'd have to do:
```
@check
def _something():
   return {'ok': True}

def check_something():
   return {'something': _something()}
```

Which feels redundant.

It'd be useful if the check decorator could take an optional name, so I could do something like:
```
@check('something')
def check_something():
   return {'ok': True}
```

And have that return 
{'something': {'ok': True}}
If it's ok, and:
{'something': {'ok': False, 'error': '...', 'stacktrace': '....'}}
if it's not.

**Comment by mwarkentin** [comment]
This sees reasonable, unfortunately I don't have any bandwidth to work on this right now. Is this something you'd be interested in opening a PR for?
