### ISSUE TITLE
Dashboard report on error

### ISSUE THREAD

**Issue by Ismael** [mwarkentin/django-watchman#127]
Say I'm checking my system and found, for example, there are no active Celery workers. 
I'd would return this from my check:

```javascript
celery_active_workers: {
  active: 0,
  ok: false
}
```

The dashboard will report Error but won't show the details.

I think the dashboard could show the whole result for easier debugging.

**Comment by mwarkentin** [comment]
This seems reasonable as well, if you're interested in working on a PR.
