### ISSUE TITLE
watchman.checks.storage hangs under OpenShift

### ISSUE THREAD

**Issue by lsloan** [mwarkentin/django-watchman#133]
I'm using watchman with an application hosted with OpenShift.  The checks I developed on my local machine (not using OpenShift) worked well, but as soon as I deployed them to the OS environment, they would fail.  Requests for `/watchman` would wait for a long time before eventually timing out.

Examining the OS logs, I found that watchman was performing my check, the database check, and the storage check, as specified in my application settings:

```python
WATCHMAN_CHECKS = (
    'watchman.checks.databases',
    'watchman.checks.storage',
    'myapp.watchmanChecks.jobsCheck',
)
```

Following the storage check, the log contained timeout info:

> 2018-12-04 17:17:34,364 DEBUG Checking '_check_storage' /usr/local/lib/python3.6/site-packages/watchman/decorators.py:27
> [2018-12-04 17:17:47 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:12)
> [2018-12-04 17:17:47 +0000] [12] [INFO] Worker exiting (pid: 12)

It would be helpful if the storage check could:

1. Have documentation that says it won't run well under OpenShift.
1. Check whether it's running under OpenShift and return an appropriate warning.
1. Have its own internal timeout.  At which time, it could return an error or warning that the check couldn't complete.  The timeout value could be configurable.

**Comment by mwarkentin** [comment]
Sorry, I missed this. I'm curious what it is about OpenStack that is causing the issue. If you use the django storage functionality to actually read / write a file to OpenStack do you see the same behaviour or it works fine?

The storage check is just doing a couple of basic operations using the configured storage: https://github.com/mwarkentin/django-watchman/blob/master/watchman/checks.py#L60-L66
