### ISSUE TITLE
bare url missing

### ISSUE THREAD

**Issue by tisdall** [mwarkentin/django-watchman#135]
The docs say that `/watchman/bare/` gives the 'bare' endpoint where it should respond with just 200 or 500, but that's not actually in the urls.py.  The docs also talk about adding your own entry to your own urls.py to access it, though.  Maybe the mention of `/watchman/bare/` was an accidental commit and it's not supposed to be accessible by default?

@jamesmallen

**Comment by mwarkentin** [comment]
@tisdall thanks for reporting this - are you referring to some other section of the docs than this? https://github.com/mwarkentin/django-watchman/blob/25902a970eab85ae5c5cc45684475a1780f8d2e2/README.rst#bare-status-view

**Comment by tisdall** [comment]
@mwarkentin - Yes, I'm referring to the [very last line of that document](https://github.com/mwarkentin/django-watchman/blob/25902a970eab85ae5c5cc45684475a1780f8d2e2/README.rst#instructions):  "5. Visit watchman bare status in your browser: http://127.0.0.1:8000/watchman/bare/ ".  That URL does not work.

**Comment by mwarkentin** [comment]
@tisdall Ah, I see - the URL is can be set to whatever you would like, but it needs to be defined in the django settings.

The piece you're referring to is how to test things out on the sample project that's provided if you check out django-watchman, and you can see that the `/bare/` url is configured in that project: https://github.com/mwarkentin/django-watchman/blob/25902a970eab85ae5c5cc45684475a1780f8d2e2/sample_project/sample_project/urls.py#L9

Would it be more clear if we used the same `bare` url here? https://github.com/mwarkentin/django-watchman/blob/25902a970eab85ae5c5cc45684475a1780f8d2e2/README.rst#bare-status-view

**Comment by tisdall** [comment]
Ah..  Yeah, I misread it then.  No, I think it's probably more clear if they're completely different and then it's obvious that it's something you manually set.  I think I assumed because it was under "/watchman/" that it should be something defined within that app.
