### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by pcraciunoiu** [mwarkentin/django-watchman#136]
Hey there, thanks for the great work on this! Any way we can get a release on pypi? The docs don't apply to the current release, so I installed off of master, but it'd be nice to have an actual release since it's been over a year, even if it's a beta or rc.

**Comment by mwarkentin** [comment]
I've pushed [django-watchman 0.16.0](https://pypi.org/project/django-watchman/0.16.0/) to pypi.. hope that helps!

**Comment by pcraciunoiu** [comment]
Yes it does, thank you!
