### ISSUE TITLE
github has wrong release tagged as "latest"

### ISSUE THREAD

**Issue by tisdall** [mwarkentin/django-watchman#138]
In https://github.com/mwarkentin/django-watchman/releases the latest release is still 0.15.0 while 0.16.0 is the latest in pypi

**Comment by mwarkentin** [comment]
Fixed, converted 0.16.0 tag into a release. Thanks!

**Comment by mwarkentin** [comment]
I've added an extra step to my release docs so this doesn't happen again.

**Comment by tisdall** [comment]
Thanks.  I appreciate that you tag your releases in Github because it makes it easier to look at the code base for particular releases.

**Comment by tisdall** [comment]
It looks like the readthedocs is stuck on 0.15.0 based on the [History page](https://django-watchman.readthedocs.io/en/stable/history.html) and also for both "stable" and "latest".  I think you can link it to the git tags.

**Comment by mwarkentin** [comment]
Looks like I need to figure out a few other things, thanks. :)
