### ISSUE TITLE
Support for Django 3.0

### ISSUE THREAD

**Issue by JBKahn** [mwarkentin/django-watchman#151]
Currently, watchman relies on https://github.com/jsocol/django-jsonview which doesn't support django 3.0. Is there a plan for this repository to support it?

**Comment by JBKahn** [comment]
What about reviving https://github.com/mwarkentin/django-watchman/pull/74 ? Thoughts?

**Comment by mwarkentin** [comment]
I see you on https://github.com/jsocol/django-jsonview/pull/47

Let's see if it looks like that can make it into a release in the near-future and roll with that? If it looks like it's getting stuck we can revisit #74?

**Comment by JBKahn** [comment]
Sure.

**Comment by JBKahn** [comment]
@mwarkentin any thoughts on dropping python 2 and django<2 with the next release?

**Comment by JBKahn** [comment]
It's been almost a week with no meaningful progress, any chance we can re-open https://github.com/mwarkentin/django-watchman/pull/74?
