### ISSUE TITLE
Storage check with defined path

### ISSUE THREAD

**Issue by daniego** [mwarkentin/django-watchman#154]
Is it possible to have the storage check to write to write into a specific path?
In our scenario the root of the MEDIA_PATH is not writable by the user which the app runs and the check fails

**Comment by mwarkentin** [comment]
Hi @daniego - this sounds like a reasonable feature! Could probably add a setting like `WATCHMAN_STORAGE_PATH` or similar which would default to the current root but could be overridden.

Unfortunately I don't have any capacity at the moment to work on this feature myself - is it something you'd be interested in contributing? If not I will ping this issue so it doesn't get closed by stalebot, but not sure when I might have a chance to work on it.

Thanks!

**Comment by daniego** [comment]
Great! I'll have some spare time in a couple weeks and look into it

**Comment by mwarkentin** [comment]
Awesome, let me know if you have any questions and I'll try to help you out!

**Comment by mwarkentin** [comment]
@daniego 

This has been released in [1.1.0](https://github.com/mwarkentin/django-watchman/releases/tag/1.1.0).

Now available on pypi: https://pypi.org/project/django-watchman/1.1.0/
