### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [mwarkentin/django-watchman#158]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'rdf4|doc|benchmark|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./watchman/decorators.py:77: DeprecationWarning: invalid escape sequence \w
  reg = re.compile('(\w+)[=] ?"?([\w-]+)"?')  # noqa: W605
```

**Comment by mwarkentin** [comment]
@tirkarthi thanks for the report, I added the fix in #159 - looks good to you?
