### ISSUE TITLE
Check Redis

### ISSUE THREAD

**Issue by hany** [mwarkentin/django-watchman#38]
This is for redis usage outside of the built-in django caching functionality, which we already have a check for.
- Will require a `WATCHMAN_REDIS_URL(S)` setting
- Is there a "standard" redis setting which we could try first?
  - `REDIS_URL`
  - `DJANGO_REDIS_URL`
- How do we know which redis lib is installed? Do we need to try to support multiples?
  - http://redis.io/clients#python
  - Start with [redis-py](https://github.com/andymccurdy/redis-py) support?
- Same checks as our [cache check](https://github.com/mwarkentin/django-watchman/blob/master/watchman/checks.py#L24-L26):
  - set key
  - get key
  - delete key

**Comment by mwarkentin** [comment]
I'm going to close this as stale, but I still think it's a good idea. For checks which aren't configurable based on default Django settings, I'm leaning towards them being installed as separate "custom" packages (eg. `django-watchman-redis-py` which would have more knowledge about how the library is expected to be configured.
