### ISSUE TITLE
django.core.cache.get_cache deprecated

### ISSUE THREAD

**Issue by ravangen** [mwarkentin/django-watchman#47]
Found in [v0.6.0](https://github.com/mwarkentin/django-watchman/tree/v0.6.0)

[django.core.cache.get_cache](https://docs.djangoproject.com/en/1.8/topics/cache/#django.core.cache.get_cache) has been deprecated since Django 1.7 in favour of using [django.core.cache.caches](https://docs.djangoproject.com/en/1.8/topics/cache/#django.core.cache.caches).

Newer versions of django packages are not implementing `get_cache`, such as [django-redis](https://github.com/niwinz/django-redis) version 4.x

**Comment by mwarkentin** [comment]
@ravangen Thanks for reporting this. At first glance, it looks like the simplest thing is probably to check the django version. If `django.VERSION < 1.7`, use the old imported function, else use the new `caches` dict-like object.

**Comment by ravangen** [comment]
Sounds reasonable. django-redis took a [similar approach](https://github.com/niwinz/django-redis/blob/master/django_redis/__init__.py#L9).
