### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by soulraven** [mwarkentin/django-watchman#50]
Any plans to migrate to Django 1.9?

**Comment by mwarkentin** [comment]
@soulraven I haven't tested w/ Django 1.9 - have you run into some issues with the pre-release?

Generally the plan is to ensure that it works with the officially supported Django releases (1.7, 1.8 at the moment), but I've opened a branch for Travis CI to test against the 1.9 beta: #51

It looks like all tests are passing on the 1.9b1 release. If you have any specific issues you've run into, I'd be happy to take a look.

**Comment by soulraven** [comment]
for the moment no, only warnings related to urlpatterns and pattern() that will not be present in 1.9

**Comment by mwarkentin** [comment]
@soulraven Ah yes, the switch to just using a list of `url`s instead of using `patterns()`: https://docs.djangoproject.com/en/1.9/releases/1.8/#django-conf-urls-patterns

It doesn't look like they actually have the deprecation version for `patterns()` in the docs as far as I can tell - can you paste the warning you're receiving?

**Comment by soulraven** [comment]
hello,
this is the warning
```
/mnt/usb500G/pyProjectsEnv/proGeekEnv/local/lib/python2.7/site-packages/watchman/urls.py:7: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got watchman.views.status). Pass the callable instead.
  url(r'^$', 'watchman.views.status', name="status"),
```

**Comment by mwarkentin** [comment]
Thanks @soulraven - looks like it should be ok through 1.9 (removed in 1.10), but this is definitely a change that should happen.

I'll look at making the change in #51.

**Comment by mwarkentin** [comment]
@soulraven This should be updated in the next release.. thanks again for the report. :smile:
