### ISSUE TITLE
setup.py should not import main package

### ISSUE THREAD

**Issue by benwebber** [mwarkentin/django-watchman#55]
The setup script should not [import the main package](https://github.com/mwarkentin/django-watchman/blob/master/setup.py#L14).

`watchman/__init__.py` may grow in the future. For example, it might be useful to raise certain objects to the top level of the API for a nicer user experience:

```
from watchman.deeply.nested import something_useful
```

At present, this would lead to an `ImportError` on installation, since setuptools would try to import `watchman.deeply.nested` before it is actually installed.

Here are some proposed solutions: https://stackoverflow.com/q/17583443/. I'm opening this as an issue, rather than a PR, since I think this is a decision for the lead developer.

I'm a fan of [bumpversion](https://github.com/peritus/bumpversion), since it would tag new releases automatically too.

Here's an example `.bumpversion.cfg`:

```
[bumpversion]
current_version = 0.8.0
commit = True
tag = True

[bumpversion:file:watchman/__init__.py]
[bumpversion:file:setup.py]
```

**Comment by mwarkentin** [comment]
Hey @benwebber, thanks for the suggestion - just to clarify, the issue would be if I tried to import something from deep in watchman within `__init__.py`, so that others could just import it directly from watchman?

Let me ponder on this for a while.. I hadn't seen bumpversion before, but it looks interesting.

**Comment by mwarkentin** [comment]
PS. Did you hear about django-watchman from my talk at Pycon today, or come across it some other way?

**Comment by mwarkentin** [comment]
Totally blanked on why your username sounded familiar.. ignore that last question. :)

Were you at Pycon though? Didn't see you there.

**Comment by benwebber** [comment]
> the issue would be if I tried to import something from deep in watchman within __init__.py, so that others could just import it directly from watchman?

Strictly speaking, you'd hit this when importing anything from under the `watchman` namespace. Raising objects to the top level of the API is a typical use case.

> Were you at Pycon though? Didn't see you there.

Indeed! Not for the full conference. I did catch your lightning talk, though, bang-up job.

**Comment by mwarkentin** [comment]
Thank you sir.. Glad you could make it!

I'll probably take a look at switching to bumpversion during sprints tomorrow. Anyone from VMF making it out to the sprints?

**Comment by benwebber** [comment]
Don't think so. Consider #56 my sprint contribution :smile_cat:
