### ISSUE TITLE
Add setting to disable/log stacktrace

### ISSUE THREAD

**Issue by robmessick** [mwarkentin/django-watchman#76]
I would like an option to suppress stacktraces from being returned by the watchman views.

Add the following new settings:

`WATCHMAN_RENDER_STACKTRACE = (True|False)` - If enabled, watchman will return the stacktrace in the json and dashboard views.

`WATCHMAN_LOG_STACKTRACE = (True|False)` -  If enabled, watchman will log stacktraces to the django logger.

**Comment by mwarkentin** [comment]
Hey @robmessick, thanks for the suggestion! This sounds like an interesting idea - I'm curious on what your use-case is for this?

Is this something you might be able to take a look at adding?

**Comment by robmessick** [comment]
I'm concerned about data leakage through the stack trace. We currently have our healthtest restricted to an internal network but I'd rather have the stack traces only available to our log indexer and end users be able to check the health of service. I'm happy to submit a PR as I find django-watchman solves my needs much better than django-health-check.

**Comment by mwarkentin** [comment]
Makes sense. Will need to see the code for the logger setting to get a better idea on how that will work. 

Please default the render setting to True so that default functionality remains the same.

**Comment by mwarkentin** [comment]
@robmessick this has been open for quite a while, and we recently added a "bare" endpoint in #114 - not quite the same as what you described here, but maybe it would fit for you. I'm going to close this, but feel free to reopen if the other changes don't cover your use case, or I'd be happy to look at a PR implementing your suggestion.
