### ISSUE TITLE
local variable 'type_overall_status' referenced before assignment

### ISSUE THREAD

**Issue by tisdall** [mwarkentin/django-watchman#77]
I'm using 0.9.0 but this seems to be an issue in the repo too.  I'm just using this project for the first time, so I suspect I have something else wrong, but there's a variable that's assigned with in an `if elif` which makes it possible to be undefined.  The line that throws the exception is: https://github.com/mwarkentin/django-watchman/blob/master/watchman/views.py#L134

From the comments and a presentation I watched, it seems that the stacktrace should be a string, but the code seems to be checking for either a `dict` or a `list`.

**Comment by mwarkentin** [comment]
Hey @tisdall, thanks for the report. I haven't seen the issue you mention before. Been a while since I looked at this code, but I believe it's looking for the type on the full check ([dict](https://github.com/mwarkentin/django-watchman/blob/master/watchman/views.py#L82-L86) or [list](https://github.com/mwarkentin/django-watchman/blob/master/watchman/views.py#L92-L105)).

Can you provide a little more information about your configuration? Are you using any custom checks or just the built-in ones? Which built-in checks are you using?

Thanks! Hope we can get this sorted out for you soon!

**Comment by tisdall** [comment]
Ah..  I see the issue.  I was going by the example you gave at the Toronto Pycon here:  https://www.youtube.com/watch?v=iEgOCY7_zGI  You've since updated it here: #21

I didn't realize I had to put the content into another dict.

**Comment by mwarkentin** [comment]
Ah, perfect. If you have that working, feel free to close this ticket. Are you using the new `@check` decorator that's provided as well?

**Comment by tisdall** [comment]
Well, you may want to expand on the documentation a little...  what I have is this:
```
def rabbitmq_connection_check():
    @check
    def do_check():
        # do the test here, exceptions will be handled by @check
        return {'ok': True}

    return {'rabbitmq': do_check()}
```

I'm not 100% sure, but it doesn't look like the `@check` would work decorating the method pointed to by `WATCHMAN_CHECKS` since it would be missing the check name.  It seems like you should be able to do a `@check('check_name')` but I can't get that to work.

**Comment by tisdall** [comment]
It seems like `@check` should do a `return {func.name: response}` instead of a `return response`, but I guess that would be a breaking change.

**Comment by mwarkentin** [comment]
Yeah, for now I think you'll need to call an inner function with that decorator (basically what we're doing here: https://github.com/mwarkentin/django-watchman/blob/master/watchman/checks.py#L68-L81).

I could be open to a change to how the decorator worked, but would need to make sure it works with checks that are lists as well (like caches/databases checks).

Any place specific in the docs that mislead you that I can look at updating?

**Comment by tisdall** [comment]
^_^  Okay, I made this:
```
def better_check(func):
    def wrapped(*args, **kwargs):
        response = check(func)(*args, **kwargs)
        return {func.func_name: response}
    return wrapped
```
So, now I can just do
```
@better_check
def rabbitmq_connection_check():
    # do the test here, exceptions will be handled
    return {'ok': True}
```

**Comment by mwarkentin** [comment]
Neat! Definitely something I might be interested in using for our built-in decorators that we provide.. thanks!

**Comment by tisdall** [comment]
Well, the example in the video is misleading, but it'd be hard to modify that (perhaps a note below the picture in the README).  But also the description under "Custom Checks" just shows a `my_check` method and it seems like you should be able to point to that directly in the `WATCHMAN_CHECKS`, but that would obviously not work.

**Comment by mwarkentin** [comment]
True - I'll try to get that updated soon.. thanks!

**Comment by tisdall** [comment]
Back to the original exception I raised at the beginning of this thread...  you may want to put an `else:` in there with an Exception explaining it's looking for a list or a dict.

**Comment by tisdall** [comment]
Any way...  I have my working rabbitmq test now.  Thanks for the help and thanks for the great project!

**Comment by mwarkentin** [comment]
That seems like a good idea as well, thanks! Let's leave this issue open until I'm able to resolve those issues.

**Comment by mwarkentin** [comment]
Let me know if you come up with any other interesting uses for it beyond RabbitMQ :)

**Comment by tisdall** [comment]
well, if you're interested in examples...  here's my finished checks for rabbitmq and celery:
```python
from django.conf import settings
from watchman.decorators import check
from kombu import Connection
from celery.task.control import inspect


def better_check(func):
    def wrapped(*args, **kwargs):
        response = check(func)(*args, **kwargs)
        return {func.func_name: response}
    return wrapped

@better_check
def rabbitmq_connection_check():
    connection = Connection(settings.BROKER_URL)
    connection.connect()  # will throw an exception if can't connect
    is_connected = connection.connected
    connection.release()
    if not is_connected:
        raise Exception('rabbitmq could not be connected to')
    return {'ok': True}

@better_check
def celery_worker_check():
    insp = inspect()
    d = insp.stats()
    if not d:
        raise Exception('No running celery workers were found')
    return {'ok': True}
```

**Comment by mwarkentin** [comment]
Nice, thanks!
