### ISSUE TITLE
Unavailable DB causes generic 500 if `ATOMIC_REQUESTS` is enabled

### ISSUE THREAD

**Issue by ulope** [mwarkentin/django-watchman#85]
When [`ATOMIC_REQUESTS`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-DATABASE-ATOMIC_REQUESTS) is enabled any database error (e.g. server unreachable) causes the generic django 500 error page to be shown. 

This can be prevented by decorating the status view with [`@transaction.non_atomic_requests`](https://docs.djangoproject.com/en/1.9/topics/db/transactions/#django.db.transaction.non_atomic_requests)

**Comment by mwarkentin** [comment]
@ulope Thanks for the report! Give me a bit of time to try to reproduce and fix - alternatively if you were interested in opening a PR, I'd be happy to review and merge.

**Comment by ulope** [comment]
Yeah, I probably have some time this week to prepare a PR.

**Comment by mwarkentin** [comment]
Awesome, not sure if there's an easy way to reproduce this in a test case, if so - that'd be ✨

Let me know if you need any help or aren't able to do the PR.
