### ISSUE TITLE
drop empty static files

### ISSUE THREAD

**Issue by tisdall** [mwarkentin/django-watchman#94]
Everything in watchman/static/ are empty files and have been since they were added by cookie-cutter...  I think it's safe to just remove them.

I noticed when I ran `manage.py collectstatic` and js/watchman.js popped up in my static directory.

**Comment by mwarkentin** [comment]
Thanks for the report! I'll take a deeper look shortly. 

Would you be open to creating a PR once I've taken a closer look?

**Comment by tisdall** [comment]
Sure, if that helps.  I currently don't have a fork and figured it would be straight forward for you to just delete the directory.

**Comment by mwarkentin** [comment]
Fixed by https://github.com/mwarkentin/django-watchman/pull/95.
