### ISSUE TITLE
Customize sender for the email check?

### ISSUE THREAD

**Issue by dlanger** [mwarkentin/django-watchman#96]
The sender for the email check is [hard-coded](https://github.com/mwarkentin/django-watchman/blob/64aa78e12257b714a0d215966bdaf9dbaf2bc5fc/watchman/checks.py#L51) to `watchman@example.com`. May email vendors (SES, Postmark, etc.) will only let you send from email address or domains you've verified with them, and there's no way to verify `watchman@example.com`.

It'd be handy if you could set the sender of this check.

**Comment by mwarkentin** [comment]
:+1:
